---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(groundhog)
pkgs <-  c("tidyverse","here", "igraph", "ggplot2", "GGally", "ggpubr")
groundhog.day <- '2022-07-25'
groundhog.library(pkgs, groundhog.day)
here::i_am("Visualization/networkTimePanel.Rmd")
```


```{r}
fullLong <- read.csv(here("Data/longIdentityNet.csv"))
fullShort <- read.csv(here("Data/shortIdentityNet.csv"))
fullData <- fullLong %>% full_join(fullShort, by = c("subID","Time"))

allTimesIDs <- unique(fullData$subID[which(fullData$Time==4)])
allTimes <- fullData[fullData$subID %in% allTimesIDs,]
tapply(allTimes$identity, allTimes$subID, function(x) length(unique(x)))

sub <- 57241

load("/Volumes/Research Project/Longitudinal Identity Network/Data/cleanedWorkspace.RData")
```

# How many timepoints per participant

```{r}
uIds <- unique(fullData$subID)
timeMat <- matrix(nrow=0, ncol=2)
for(i in uIds){
 uTime <- unique(fullData$Time[fullData$subID==i]) 
 timeMat <- rbind(timeMat, cbind(rep(i,length(uTime)), uTime))
}
colnames(timeMat) <- c("subID", "time")
timeMat <- as.data.frame(timeMat)
timeMat <- timeMat %>% arrange(subID, time)
```

# Generate and print all plots for all participants and all timepoints

```{r}
for(s in uIds){
  
  maxTime <- max(timeMat$time[timeMat$subID==s])
  listGraphs <- lapply(1:maxTime, function(x) get(paste0("subIGraphW.",s,"_",x)))
  
  print(paste0("Subject ",s))

  for(i in 1:maxTime){
    
    if(vcount(listGraphs[[i]])<2){ # if only 1 identity, skip
      next
    }
    
    if(ecount(listGraphs[[i]]) > 0){
      
      set.seed(2)
      
      plotSingle <- ggnet2(listGraphs[[i]], alpha = 0.75, size = "degree", color = "phono",
                              edge.color = "grey", edge.size = E(listGraphs[[i]])$weight, mode = "kamadakawai", label = T, layout.exp = .65) + 
      guides(color = "none", size = "none") +
        theme( panel.border = element_rect(colour = "black", fill=NA, size=5) )
      
    }else if(ecount(listGraphs[[i]])==0){
      
    plotSingle <- ggnet2(listGraphs[[i]], alpha = 0.75, size = "degree", color = "phono", mode = "kamadakawai", label = T, layout.exp = .65) + 
      guides(color = "none", size = "none") +
  theme(plot.background = element_rect(color = "black", size = 3))

    }
    
    assign(paste0('p',i), plotSingle)
    
    print(paste0("Time ",i))
    print(plotSingle)

  }
  
  # Plot different grid arrange depending on how many timepoints appeared
  if(maxTime==1){
    plotComb <- p1
  }else if(maxTime==2){
    plotComb <- ggpubr::ggarrange(p1,p2,nrow=2,ncol=1,labels=c("T1","T2"))
  }else if(maxTime==3){
    plotComb <- ggpubr::ggarrange(p1,p2,p3,nrow=3,ncol=1,labels=c("T1","T2","T3"))
  }else if(maxTime==4){
    plotComb <- ggpubr::ggarrange(p1,p2,p3,p4,nrow=4,ncol=1,labels=c("T1","T2","T3","T4"))
  }
  
  plotComb <- annotate_figure(plotComb, top = text_grob(paste0("Subject", s), 
               color = "black", face = "bold", size = 14)) + theme(plot.background = element_rect(color = "red", size = 3))
  
}

```
