---
title: "R Notebook"
output: html_notebook
---

```{r}
library(groundhog)
pkgs <-  c("tidyverse","here", "igraph")
groundhog.day <- '2022-07-25'
groundhog.library(pkgs, groundhog.day)
here::i_am("cleaning/idNetCleaning.Rmd")
```

```{r}
devtools::source_url("https://raw.githubusercontent.com/JacobElder/MiscellaneousR/master/assortativityNA.R")
```


```{r}
T1raw <- data.table::fread(here("cleaning/input/rawT1.csv"))
T2raw <- data.table::fread(here("cleaning/input/rawT2.csv"))
T3raw <- data.table::fread(here("cleaning/input/rawT3.csv"))
T4raw <- data.table::fread(here("cleaning/input/rawT4.csv"))

setwd("~/Google Drive/Volumes/")
posDf <- read.csv("./Research Project/Trait Network_Behaviral/generating network/output/adjacencyMatrix_p.csv")
posMat <- as.matrix(posDf)
posGraph <- graph.adjacency(posMat)
negDf <- read.csv("./Research Project/Trait Network_Behaviral/generating network/output/adjacencyMatrix_n.csv")
negMat <- as.matrix(negDf)
negGraph <- graph.adjacency(negMat)
```

# Create functions

```{r}
is.emptyString <- function(input){
  if(input==''){
    output <- TRUE
  }else{
    output <- FALSE
  }
  return(output)
}
```


# Fixed duplicated names

```{r}
# # Duplicate columns
# wrong <- which(colnames(T1raw)=="I9_Sims_1")[1]
# colnames(T1raw)[wrong:(wrong+14)] <- paste0("I8_Sims_",1:15)

# Fix the identity nominations columns
noms <- which(colnames(T1raw)=="Identity Nominations_1")[1]
colnames(T1raw)[noms:(noms+14)] <- paste0("IdNoms_",1:15)

T1raw <- as_tibble(T1raw)
T2raw <- as_tibble(T2raw)
T3raw <- as_tibble(T3raw)
T4raw <- as_tibble(T4raw)
```

```{r}
T1raw <- T1raw %>% rename(subID = id)
T2raw <- T2raw %>% rename(subID = id)
T3raw <- T3raw %>% rename(subID = id)
T4raw <- T4raw %>% rename(subID = id)

replacement <- 500000
for(i in 1:nrow(T1raw)){
  if(is.na(T1raw$subID[i]) | is.emptyString(T1raw$subID[i])){
    T1raw$subID[i] <- 500000
    replacement <- replacement + 1
  }
}

t1tot2subs <- intersect(T1raw$subID, T2raw$subID)

# Two 60549's for some reason... Relabeling the first, they didn't do any other timepoints
T1raw[T1raw$subID==60549,][1,]$subID <- "6054912345"

#T1raw <- T1raw[T1raw$subID %in% t1tot2subs,]

T1raw <- T1raw[!duplicated(T1raw$subID),]
T2raw <- T2raw[!duplicated(T2raw$subID),]
T3raw <- T3raw[!duplicated(T3raw$subID),]
T4raw <- T4raw[!duplicated(T4raw$subID),]
```

```{r}


idMat <- matrix(NA,ncol=16,nrow=nrow(T1raw))
for(n in 1:nrow(T1raw) ){
  identities <- T1raw %>% 
    select(IdNoms_1:IdNoms_15) %>%
    slice(n) %>%
    as_vector()
  
  idIndices <- identities %>%
    map(is.emptyString) %>%
    unlist()
  
  identities[idIndices] <- NA
  
  idMat[n,] <- c(T1raw$subID[n], identities)
  
  
    
}

idMat <- as_tibble(idMat)
colnames(idMat) <- c("subID",paste0("I",1:16))
```

```{r}
allNA <- which( rowSums(is.na(idMat[,2:16])) != 15 ) # which rows are not all NA
notallNAsubs <- idMat$subID[allNA]
T1raw <- T1raw[T1raw$subID %in% notallNAsubs,]
T2raw <- T2raw[T2raw$subID %in% notallNAsubs,]
T3raw <- T3raw[T3raw$subID %in% notallNAsubs,]
T4raw <- T4raw[T4raw$subID %in% notallNAsubs,]
```

```{r}
T1s <- unique(T1raw$subID)
T2s <- unique(T2raw$subID)
T3s <- unique(T3raw$subID)
T4s <- unique(T4raw$subID)
```

```{r}
for(k in 1:4){
  
  raw <- get(paste0("T",k,"raw"))
  uIds <- unique(raw$subID)
  # column names
  idSubs <- raw %>%
    select(contains("_Relations"))
  for(n in 1:nrow(raw)){
    i <- raw$subID[n]
    
    idNames <- idMat[idMat$subID==i,2:16] %>% as_vector() %>% na.omit()
    numIdentities <- sum(!is.na(idMat[idMat$subID==i,2:16]))
    
    # subset subject row
    subDf <- raw[raw$subID==i,]
    # generate empty matrix
    subMat <- matrix(data = 0, nrow = numIdentities, ncol = numIdentities)
    subMatW <- matrix(data = 0, nrow = numIdentities, ncol = numIdentities)
    for(c in 1:numIdentities){
      # subset identity "c"
      j <- idSubs[n,c]
      # split words by comma
      selectWord <-strsplit(as.character(idSubs[n,c][[1]]),",") 
      if(length(selectWord[[1]])==0){
        next
      }
      
      # which column index are select identities
      ######rowSub <-which(idNames %in% selectWord[[1]])
      # populate 1s for select identities in row and column for undirected
      # DO BELOW ONLY IF YOU WANT DIRECTED NETWORK
      subMat[c,as.numeric(unlist(selectWord))] <- 1 # Unweighted matrix
      # ALSO DO BELOW IF YOU WANT UNDIRECTED (SYMMETRIC) NETWORK
      subMat[as.numeric(unlist(selectWord)),c] <- 1 # Unweighted matrix
      diag(subMat) <- 0 # Set diagonal to 0s if participants nominated any self-connections
      for(p in unlist(selectWord)){
        
      if(subMatW[c,as.numeric(unlist(p))]==0){
        
        subMatW[c,as.numeric(unlist(p))]  <- as.numeric ( raw[n,paste0("I",c,"_Sims_",as.numeric(unlist(p) ))] ) / 11 # Weighted matrix
        
        subMatW[as.numeric(unlist(p)),c]  <- as.numeric ( raw[n,paste0("I",c,"_Sims_",as.numeric(unlist(p) ))] ) / 11 # Weighted matrix
        
      }else if(subMatW[c,as.numeric(unlist(p))]>0){
        
        subMatW[c,as.numeric(unlist(p))]  <- mean(c(subMatW[c,as.numeric(unlist(p))], as.numeric ( raw[n,paste0("I",c,"_Sims_",as.numeric(unlist(p) ))] ) / 11 )) # Weighted matrix
        
        subMatW[as.numeric(unlist(p)),c]  <- mean(c(subMatW[as.numeric(unlist(p)),c], as.numeric ( raw[n,paste0("I",c,"_Sims_",as.numeric(unlist(p) ))] ) / 11 )) # Weighted matrix
        
      }
        
      }
      # if participant didn't indicate weight, replace with 0
      subMatW[is.na(subMatW)] <- 0
      # Flipped direction of fraction so more overlap is closer between identities
      
      diag(subMatW) <- 0 # Set diagonal to 0s if participants nominated any self-connections
  }
    rownames(subMat) <- idNames
    colnames(subMat) <- idNames
    
    rownames(subMatW) <- idNames
    colnames(subMatW) <- idNames
  
      # convert to graph
    subGraph <- graph.adjacency(subMat, mode="undirected")
    subGraphW <- graph.adjacency(subMatW, weighted = T, mode="undirected")
    # label
    assign(paste0("subIMat.",i,"_",k),subMat)
    assign(paste0("subIGraph.",i,"_",k),subGraph)
    
    assign(paste0("subIMatW.",i,"_",k),subMatW)
    assign(paste0("subIGraphW.",i,"_",k),subGraphW)
  }

  
}
```

```{r}
computeNeighbors <- function(graph, label, variable, type = "all"){
  curNeigh <- neighbors(graph, label, mode = type)
  curGraph <- induced.subgraph(graph, curNeigh)
  impInd <- which(!is.na(vertex_attr(curGraph, variable)))
  impGraph <- induced.subgraph(curGraph, impInd)
  valuesImp <- vertex_attr(impGraph, variable)
  neighAve <- mean(valuesImp, na.rm = TRUE)
  return(neighAve)
}
computeNeighbors <- compiler::cmpfun(computeNeighbors)
```


```{r}
fullLong <- matrix(nrow=0,ncol=52)

fullShort <- matrix(nrow=0,ncol=32)

varnames <- c("M", "I", "P", "Ent", "Sim", "Proto", "SzSch", "SzUS", "A", 
"D", "ThermIn", "ThermOut", "MemUnc", "IdUnc", "Should", "Consist", 
"Salient", "Ideal", "BExp", "GExp", "BelPer")
for(i in 1:4){
  uIds <- get(paste0("T",i,"s"))
  raw <- get(paste0("T",i,"raw"))
  timeShort <- matrix(nrow=0,ncol=32)
  timeLong <- matrix(nrow=0,ncol=52)
  for(j in 1:length(uIds)){
    subID <- uIds[j]
    subNetUW <- get(paste0("subIGraph.",subID,"_",i))
    subNetW <- get(paste0("subIGraphW.",subID,"_",i))
    numIdentities <- sum(!is.na(idMat[idMat$subID==subID,2:16]))
    
    M <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_M")])
    I <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_I")])
    P <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_P")])
    St <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_St")])
    Ent <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Ent")])
    Sim <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Sim")])
    Proto <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Proto")])
    SzSch <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Sz_1")])
    SzUS <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Sz_13")])
    A <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_A")])
    D <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_D")])
    ThermIn <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Therm_1")])
    ThermOut <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Therm_2")])
    MemUnc <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_MemUncert")])
    IdUnc <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_IdUncert")])
    Should <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Should")])
    Consist <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Consist")])
    Salient <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Salient")])
    Ideal <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Ideal")])
    BExp <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_BExp")])
    GExp <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_GExp")])
    BelPer <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_BelPer")])
    
    V(subNetUW)$M <- M
    V(subNetUW)$I <- I
    V(subNetUW)$P <- P
    V(subNetUW)$St <- St
    V(subNetUW)$Ent <- Ent
    V(subNetUW)$Sim <- Sim
    V(subNetUW)$Proto <- Proto
    V(subNetUW)$SzSch <- SzSch
    V(subNetUW)$SzUS <- SzUS
    V(subNetUW)$A <- A
    V(subNetUW)$D <- D
    V(subNetUW)$ThermIn <- ThermIn
    V(subNetUW)$ThermOut <- ThermOut
    V(subNetUW)$MemUnc <- MemUnc
    V(subNetUW)$IdUnc <- IdUnc
    V(subNetUW)$Should <- Should
    V(subNetUW)$Consist <- Consist
    V(subNetUW)$Salient <- Salient
    V(subNetUW)$Ideal <- Ideal
    V(subNetUW)$BExp <- BExp
    V(subNetUW)$GExp <- GExp
    V(subNetUW)$BelPer <- BelPer
    
    subLong <- 
      cbind(subID,
          as_vector(idMat[idMat$subID==subID,2:(numIdentities+1)]),
          seq(1,numIdentities),
          i,
          degree(subNetUW),
          degree(subNetUW,mode="out"),
          degree(subNetUW,mode="in"),
          strength(subNetW),
          M,
          I,
          P,
          St,
          Ent,
          Sim,
          Proto,
          SzSch,
          SzUS,
          A,
          D,
          ThermIn,
          ThermOut,
          MemUnc,
          IdUnc,
          Should,
          Consist,
          Salient,
          Ideal,
          BExp,
          GExp,
          BelPer
          )
    
    subLong <- cbind(subLong,
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "M", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "I", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "P", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "St", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Ent", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Sim", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Proto", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "SzSch", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "SzUS", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "A", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "D", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "ThermIn", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "ThermOut", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "MemUnc", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "IdUnc", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Should", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Consist", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Salient", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "Ideal", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "BExp", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "GExp", "all"))),
    unlist(lapply(1:numIdentities, function(x) computeNeighbors(subNetUW, x, "BelPer", "all")))
    
    )
    
    
    
    # identity to identity network total edges
    idEdgT <- ecount(subNetUW)
    # density
    density <- edge_density(subNetUW)
    # average distance
    aveDist <- mean_distance(subNetUW)
    # clustering coefficient
    idTrans <- transitivity(subNetUW, "global")
    # small worldness
    # global efficiency
    globEff <- brainGraph::efficiency(subNetUW, type = "global")
    # Mean strength
    meanStre <- mean(strength(subNetW))
    # Sum strength
    sumStre <- sum(strength(subNetW))
    # Similarity mean
    idSimGlob <- (similarity(subNetW, method = "dice"))%>% .[lower.tri(.)] %>% mean()
    # Ave strength
    # assortativity identification
    homophs <- unlist(
      lapply(varnames, function(x) assortativityNA(subNetUW, as.numeric(
      vertex_attr(subNetUW, x) +
      rnorm(1, 0, .00001), 
      directed=F
      )))
    )
    names(homophs) <- paste0(varnames,"_homoph")
    
    subShort <- c(subID,i,idEdgT,density,aveDist,idTrans,globEff, numIdentities, meanStre, sumStre, idSimGlob, homophs)
    
    timeLong <- rbind(timeLong, subLong)
    timeShort <- rbind(timeShort, subShort)
  }
  fullLong <- rbind(fullLong, timeLong)
  fullShort <- rbind(fullShort, timeShort)
}

fullLong <- as.data.frame(fullLong)
begNames <- c("subID","identity","idCode","Time", "degree", "outdegree", "indegree", "strength")
colnames(fullLong)[1:length(begNames)] <- begNames
neighNames <- paste0(colnames(fullLong)[which(colnames(fullLong)=="M"):which(colnames(fullLong)=="BelPer")],"_neigh")
colnames(fullLong)[(which(colnames(fullLong)=="BelPer")+1):((which(colnames(fullLong)=="BelPer"))+length(neighNames))] <- neighNames
fullLong[3:ncol(fullLong)] <- apply(fullLong[3:ncol(fullLong)], 2, as.numeric)

begNames <- c("subID","Time","edgeTot","dense","aveDist","idTrans","globEff","numID","meanStre","sumStre","idSimGlob")
colnames(fullShort)[1:length(begNames)] <- begNames
fullShort <- as.data.frame(fullShort)
```

```{r}

T1raw <- T1raw %>% mutate(across(contains("Race_Type"), ~ case_when(.==1 ~ "Black/African-American", 
                                                     .==2 ~ "Hispanic/Latino",
                                                     .==3 ~ "White/Causasian",
                                                     .==4 ~ "Asian",
                                                     .==5 ~ "Pacific Islander",
                                                     .==6 ~ "Native-American",
                                                     .==7 ~ "Indian/South Asian",
                                                     .==8 ~ "Mixed",
                                                     .==9 ~ "Middle-Eastern",
                                                     .==10 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Gen_Type"), ~ case_when(.==1 ~ "Cisgender Male", 
                                                     .==2 ~ "Cisgender Female",
                                                     .==3 ~ "White/Causasian",
                                                     .==4 ~ "Nonbinary",
                                                     .==5 ~ "Transgender Male",
                                                     .==6 ~ "Transgender Female",
                                                     .==7 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Sex_Type"), ~ case_when(.==1 ~ "Heterosexual", 
                                                     .==2 ~ "Homosexual",
                                                     .==3 ~ "Bisexual",
                                                     .==4 ~ "Asexual",
                                                     .==5 ~ "Pacific Islander",
                                                     .==6 ~ "Pansexual",
                                                     .==7 ~ "Queer",
                                                     .==8 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Rel_Type"), ~ case_when(.==1 ~ "Catholic", 
                                                     .==2 ~ "Christian",
                                                     .==3 ~ "Islamic",
                                                     .==4 ~ "Hindu",
                                                     .==5 ~ "Buddhist",
                                                     .==6 ~ "Jewish",
                                                     .==7 ~ "Sikh",
                                                     .==8 ~ "Atheist",
                                                     .==9 ~ "Agnostic",
                                                     .==10 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("SES_Type"), ~ case_when(.==1 ~ "Upper Class", 
                                                     .==2 ~ "Upper Middle Class",
                                                     .==3 ~ "Middle Class",
                                                     .==4 ~ "Lower Middle Class",
                                                     .==5 ~ "Working Class",
                                                     .==6 ~ "Poor",
                                                     .==7 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Occup_Type"), ~ case_when(.==1 ~ "Student", 
                                                     .==2 ~ "Agriculture/Food/Farming",
                                                     .==3 ~ "Architecture/Construction",
                                                     .==4 ~ "Business/Management/Administration",
                                                     .==5 ~ "Arts/Audio/Video Tech/Communications",
                                                     .==6 ~ "Finance",
                                                     .==7 ~ "Government and Public Administration",
                                                     .==8 ~ "Health/Medicine",
                                                     .==9 ~ "Hospitality/Tourism",
                                                     .==10 ~ "Entertainment",
                                                     .==11 ~ "Marketing/Sales/Service", 
                                                     .==12 ~ "Information Technology",
                                                     .==13 ~ "Law/Public Safety/Corrections/Security",
                                                     .==14 ~ "Manufacturing",
                                                     .==15 ~ "Marketing/Sales/Service",
                                                     .==16 ~ "Private Sector Science/Technology",
                                                     .==17 ~ "Academic Science/Technology",
                                                     .==18 ~ "Transportation/Distribution/Logistics",
                                                     .==19 ~ "Unemployed",
                                                     .==20 ~ "Other/Not Listed"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Pol_Type"), ~ case_when(.==1 ~ "Democrat", 
                                                     .==2 ~ "Republican",
                                                     .==3 ~ "Libertarian",
                                                     .==4 ~ "Green",
                                                     .==5 ~ "Socialist",
                                                     .==6 ~ "Independent",
                                                     .==7 ~ "Other/Not Listed"
                                                     )))


T1raw <- T1raw %>% mutate(across(contains("Fam_Type"), ~ case_when(.==1 ~ "Mother", 
                                                     .==2 ~ "Father",
                                                     .==3 ~ "Son",
                                                     .==4 ~ "Daughter",
                                                     .==5 ~ "Sister",
                                                     .==6 ~ "Brother",
                                                     .==7 ~ "Uncle",
                                                     .==8 ~ "Aunt",
                                                     .==9 ~ "Grandfather",
                                                     .==10 ~ "Granddaughter",
                                                     .==11 ~ "Nephew", 
                                                     .==12 ~ "Niece",
                                                     .==13 ~ "Other",
                                                     .==14 ~ "Grandmother",
                                                     .==15 ~ "Grandson"
                                                     )))


T1raw <- T1raw %>% mutate(across(contains("Friend_Type"), ~ case_when(.==1 ~ "Best Friend", 
                                                     .==2 ~ "Friend",
                                                     .==3 ~ "Acquaintance",
                                                     .==4 ~ "Other"
                                                     )))

T1raw <- T1raw %>% mutate(across(contains("Hob_Type"), ~ case_when(.==1 ~ "Art/Craft", 
                                                     .==2 ~ "Music",
                                                     .==3 ~ "Sports",
                                                     .==4 ~ "Gardening",
                                                     .==5 ~ "Cooking/Baking",
                                                     .==6 ~ "Outdoors",
                                                     .==7 ~ "Dancing",
                                                     .==8 ~ "Gaming",
                                                     .==9 ~ "Movies/TV",
                                                     .==10 ~ "Social",
                                                     .==11 ~ "Travel/Exploration", 
                                                     .==12 ~ "Driving",
                                                     .==13 ~ "Collection",
                                                     .==14 ~ "Reading",
                                                     .==15 ~ "Brewing",
                                                     .==16 ~ "Manufacturing/Building",
                                                     .==17 ~ "Running",
                                                     .==18 ~ "Weightlifting",
                                                     .==19 ~ "Other/Not Listed"
                                                     )))


```


```{r}

  raw <- get(paste0("T","1","raw"))
  uIds <- unique(raw$subID)
  
  fullMat <- matrix(ncol=4,nrow=0)
  
for(j in 1:length(uIds)){
  
  subID <- uIds[j]
  numIdentities <- sum(!is.na(idMat[idMat$subID==subID,2:16]))
 
    CatsCols <- as.numeric(raw[raw$subID==subID, paste0("I",1:numIdentities,"_Cat")])
    CategV <- matrix(ncol=1,nrow=numIdentities)
    GroupV <- matrix(ncol=1,nrow=numIdentities)
    TypeV <- matrix(ncol=1,nrow=numIdentities)
    
    for(z in 1:numIdentities){
      
      if(!is.na(CatsCols[z])){
        
      if(CatsCols[z]==1){
        C <- "Race"
        
      }else if(CatsCols[z]==2){
        C <- "Gen"
         
      }else if(CatsCols[z]==3){
        C <- "Sex"
         
      }else if(CatsCols[z]==4){
        C <- "Pol"
         
      }else if(CatsCols[z]==5){
        C <- "SES"
         
      }else if(CatsCols[z]==6){
        C <- "Rel"
         
      }else if(CatsCols[z]==7){
        C <- "Occup"
         
      }else if(CatsCols[z]==8){
        C <- "Hob"
         
      }else if(CatsCols[z]==9){
        C <- "Fam"
         
      }else if(CatsCols[z]==10){
        C <- "Friend"
         
      }else if(CatsCols[z]==11){
        C <- "Other"
      }
        
      }else{
        C <- NA
      }
        
    if(!is.na(CatsCols[z])){
      
      if(CatsCols[z]==11){
      #Group <- as.numeric(raw[raw$subID==subID, paste0("I",z,"_Cat_11_TEXT")])
        Type <- as.character(raw[raw$subID==subID, paste0("I",z,"_Cat_11_TEXT")])
        
        # if(is.na(Type)){
        #   break
        # }
        
      }else if (CatsCols[z]<11){
      #Group <- T1raw[paste0("I",z,"_",C)]
        Type <- as.character(raw[raw$subID==subID, paste0("I",z,"_",C,"_Type")]) 
        
        # if(is.na(Type)){
        #   break
        # }
        
      }
      
    }else{
      
      Type <- NA
      
    }  
   
    CategV[z,1] <- C
    #GroupV[z,1] <- Group
    TypeV[z,1] <- Type
      
    }
    

    subMat <- cbind(subID=rep(subID,numIdentities), seq(1,numIdentities),  CategV, TypeV)
    fullMat <- rbind(fullMat,subMat)
  
}
  
identityDf <-  as.data.frame(fullMat)
colnames(identityDf) <- c("subID","idCode","Categ","Group")
fullLong <- merge(fullLong, identityDf, by=c("subID","idCode"))
fullLong <- fullLong %>% select(subID, idCode, identity, Categ, Group, everything())
```

```{r}
T1raw <- T1raw %>% mutate(across(ends_with("_Cat"), ~ case_when(.==1 ~ "Racial/Ethnic", 
                                                     .==2 ~ "Gender",
                                                     .==3 ~ "Sexual Orientation",
                                                     .==4 ~ "Political",
                                                     .==5 ~ "Socioeconomic",
                                                     .==6 ~ "Religion",
                                                     .==7 ~ "Occupation",
                                                     .==8 ~ "Hobby/Ability",
                                                     .==9 ~ "Family",
                                                     .==10 ~ "Friend",
                                                     .==11 ~ "Other"
                                                     )))
```



# Remove duplicate rows

```{r}
# fullLong[!duplicated(fullLong), ]
# 
# fullLong %>% distinct()

test <- subset(fullLong, subID==59360)
```


# Change

```{r}
for(n in 2:4){
  uIds <- unique(fullLong$subID[fullLong$Time==n])
  for(j in 1:length(uIds)){
    subID <- uIds[j]
    uIdentities <- unique(fullLong$identity[fullLong$subID==subID])
    for(k in 1:length(uIdentities)){
      identity <- uIdentities[k]
      
      # Identification Change
      
      fullLong$I_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$I[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$I[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Identification Previous
      
      fullLong$I_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$I[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Degree Change
      
      fullLong$deg_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$degree[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$degree[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Degree Previous
      
      fullLong$deg_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$degree[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Strength Change
      
      fullLong$streng_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$strength[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$strength[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Strength Previous
      
      fullLong$streng_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$strength[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # IdUnc Change
      
      fullLong$IdUnc_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # IdUnc Previous
      
      fullLong$IdUnc_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # MemUnc Change
      
      fullLong$MemUnc_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$MemUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$MemUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # MemUnc Previous
      
      fullLong$MemUnc_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$MemUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # P Change
      
      fullLong$P_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$P[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$P[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # P Previous
      
      fullLong$P_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$P[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # St Change
      
      fullLong$St_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$St[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$St[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # St Previous
      
      fullLong$St_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$St[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # Ent Change
      
      fullLong$Ent_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Ent[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$Ent[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Ent Previous
      
      fullLong$Ent_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Ent[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # IdUnc Change
      
      fullLong$IdUnc_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # IdUnc Previous
      
      fullLong$IdUnc_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # Sim Change
      
      fullLong$Sim_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Sim[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$Sim[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Sim Previous
      
      fullLong$Sim_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Sim[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # Proto Change
      
      fullLong$Proto_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Proto[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$Proto[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # Proto Previous
      
      fullLong$Proto_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$Proto[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
            # A Change
      
      fullLong$A_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$A[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$A[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # A Previous
      
      fullLong$A_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$A[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # D Change
      
      fullLong$D_Change[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$D[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] - fullLong$D[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
      # D Previous
      
      fullLong$D_Prev[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- fullLong$D[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==(n-1)]
      
    }
  }
}
```

# Cumulative

```{r}
for(n in 1:4){
  uIds <- unique(fullLong$subID[fullLong$Time==n])
  for(j in 1:length(uIds)){
    subID <- uIds[j]
    uIdentities <- unique(fullLong$identity[fullLong$subID==subID])
    for(k in 1:length(uIdentities)){
      identity <- uIdentities[k]
      
      fullLong$I_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$I[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$I_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$I[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
      fullLong$Consist_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$Consist[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$Consist_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$Consist[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
      fullLong$Salient_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$Salient[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$Salient_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$Salient[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
    fullLong$St_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$St[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$St_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$St[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
    fullLong$GExp_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$GExp[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$GExp_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$GExp[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
    fullLong$BExp_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$BExp[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$BExp_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$BExp[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
      fullLong$Should_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$Should[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$Should_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$Should[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
      fullLong$IdUnc_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$IdUnc_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$IdUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
      fullLong$MemUnc_Cum[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- sum(fullLong$MemUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      fullLong$MemUnc_Ave[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time==n] <- mean(fullLong$MemUnc[fullLong$subID==subID & fullLong$identity==identity & fullLong$Time %in% 1:n],na.rm=T)
      
    }
  }
}
```

# Need for Cognition

```{r}
NFCrevcols = c("NFC-6_3", "NFC-6_4")
T1raw[ ,NFCrevcols] = 8 - T1raw[ ,NFCrevcols]
ind1 <- grep("NFC-6_1", colnames(T1raw))
ind1<-min(ind1)
ind2<- grep("NFC-6_6", colnames(T1raw))
ind2<-max(ind2)
# Compute scores for Need for Cog
T1raw$NFC = rowMeans(T1raw[, ind1:ind2], na.rm = TRUE)

psych::alpha(T1raw[ind1:ind2])
```
# Self-Esteem

```{r}
# Reverse code Rosenberg Self-Esteem items
SErevcols = c("RSE2", "RSE5", "RSE6", "RSE8", "RSE9")
T1raw[ ,SErevcols] = 5 - T1raw[ ,SErevcols]
ind1 <- grep("^RSE1$", colnames(T1raw))
ind1<-min(ind1)
ind2<- grep("^RSE10$", colnames(T1raw))
ind2<-max(ind2)
# Compute scores for Rosenberg Self-Esteem
T1raw$SE = rowMeans(T1raw[, ind1:ind2], na.rm = TRUE)
T1raw$SE <- 5 - T1raw$SE
psych::alpha(T1raw[ind1:ind2])
```

## Self-Concept Clarity

```{r}
# Reverse code Self-Concept Clarity Scale items
SCC_revcols = c("SCC1", "SCC2", "SCC3", "SCC4", "SCC5", "SCC7", 
                 "SCC8", "SCC9", "SCC10", "SCC12")
T1raw[ ,SCC_revcols] = 6 - T1raw[ ,SCC_revcols]
ind1 <- grep("SCC1", colnames(T1raw))
ind1<-min(ind1)
ind2<- grep("SCC12", colnames(T1raw))
ind2<-max(ind2)
# Compute score for Self-Concept Clarity Scale items
T1raw$SCC = rowMeans(T1raw[,ind1:ind2], na.rm = TRUE)

psych::alpha(T1raw[ind1:ind2])
```

```{r}
fullLong <- fullLong %>%
  mutate(bias = ThermIn - ThermOut)
biasShort <- fullLong %>% 
  group_by(subID) %>%
  summarise(totalBias = mean(bias, na.rm=T),
            varBias = sd(bias, na.rm=T))
fullShort <- T1raw %>% select(subID, SE, SCC, NFC) %>% right_join(fullShort, by = "subID")
biasShort$subID <- as.double(biasShort$subID)
fullShort$subID <- as.double(fullShort$subID)
fullShort <- fullShort %>% left_join(biasShort, by = "subID")
```

```{r}
```



```{r}
write.csv(fullLong,"../Data/longIdentityNet.csv", row.names = F)
write.csv(fullShort,"../Data/shortIdentityNet.csv", row.names = F)
arrow::write_parquet(fullLong,"../Data/longIdentityNet.parquet")
arrow::write_parquet(fullShort,"../Data/shortIdentityNet.parquet")
save.image("/Volumes/Research Project/Longitudinal Identity Network/Data/cleanedWorkspace.RData")
```




